name: Publish
on:
  push:
    branches: [master]
jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.github_token }}
        publish_dir: ${{ github.workspace }}
        enable_jekyll: false
        user_name: ${{ github.actor }}
        user_email: ${{ github.actor }}@users.noreply.github.com
        commit_message: ${{ github.event.head_commit.message }}
